/**
 * POST /api/verify/submit — self-service tool certification entry point.
 *
 * Flow (see plan §5, §10):
 *   1. Validate the submission against the manifest-mirroring zod schema.
 *   2. Rate-limit per client + per repo.
 *   3. Reject if the slug is already taken in the engine repo.
 *   4. New repos require admin approval before their first run → recorded as
 *      "approved-pending" and NOT dispatched until an admin approves the repo.
 *   5. Approved repos: commit manifest.yml + Dockerfile to tools/<slug>/ and
 *      dispatch the verify workflow with a unique dispatch_id for correlation.
 *
 * STRhub never stores tool source code — only the verification metadata.
 */
import { type NextRequest, NextResponse } from "next/server";
import {
  submissionSchema,
  deriveSlug,
  newDispatchId,
  isRemoteFixture,
  INPUT_TYPES,
} from "@/lib/verified/submission";
import {
  parseBed3,
  validateRegions,
  fetchPanel,
} from "@/lib/verified/validate-regions";
import {
  buildManifestYaml,
  generateDockerfile,
  REGIONS_ASSET_PATH,
} from "@/lib/verified/manifest";
import {
  ENGINE_REPO,
  GitHubConfigError,
  GitHubApiError,
  getFileContent,
  putFile,
  dispatchWorkflow,
} from "@/lib/verified/github";
import {
  checkRateLimit,
  hashClient,
  isRepoApproved,
  normalizeRepo,
  recordSubmission,
} from "@/lib/verified/store";
import { notifyNewPendingSubmission } from "@/lib/email";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

function clientIp(request: NextRequest): string {
  const fwd = request.headers.get("x-forwarded-for");
  if (fwd) return fwd.split(",")[0].trim();
  return request.headers.get("x-real-ip") || "unknown";
}

/**
 * The BYOR fixture must be PUBLIC at run time (§10). Verify the raw URL is
 * reachable before dispatching so the author gets a clear message instead of a
 * silently N/A "own" leg later.
 */
/**
 * Which repository a slug already belongs to, read from its committed manifest.
 *
 * A slug is derived from the tool name, version and input type, all of which the
 * submitter chooses, so two different repositories can land on the same one. That
 * makes "does tools/<slug>/manifest.yml exist?" the wrong question for both the
 * approval gate and the overwrite decision: it answers "is this slug taken", not
 * "is this the same author coming back". Returns null when there is no manifest.
 */
async function manifestOwner(slug: string): Promise<string | null> {
  const yml = await getFileContent(`tools/${slug}/manifest.yml`);
  if (!yml) return null;
  // The manifest is machine-generated by buildManifestYaml (or hand-written in the
  // same shape), so source.repo is a plain scalar on its own line.
  const m = yml.match(/^\s{2}repo:\s*["']?(\S+?)["']?\s*$/m);
  return m ? m[1] : null;
}

async function remoteFixtureReachable(
  repo: string,
  ref: string,
  path: string
): Promise<boolean> {
  const slug = repo.replace(/\.git$/, "").replace(/^https:\/\/github\.com\//, "");
  const url = `https://raw.githubusercontent.com/${slug}/${ref}/${path.replace(/^\//, "")}`;
  try {
    const res = await fetch(url, { method: "HEAD", cache: "no-store" });
    return res.ok;
  } catch {
    return false;
  }
}

export async function POST(request: NextRequest) {
  let body: unknown;
  try {
    body = await request.json();
  } catch {
    return NextResponse.json({ ok: false, error: "Invalid JSON body" }, { status: 400 });
  }

  const parsed = submissionSchema.safeParse(body);
  if (!parsed.success) {
    return NextResponse.json(
      { ok: false, error: "Validation failed", issues: parsed.error.flatten() },
      { status: 400 }
    );
  }
  const sub = parsed.data;
  const slug = deriveSlug(sub.tool.name, sub.tool.version, sub.inputs.type);
  // The raw address never leaves this request: records go to public repos, so
  // only the salted digest is stored. The address itself is used solely for the
  // admin notification email.
  const ip = clientIp(request);
  const clientHash = hashClient(ip);

  // 1b. BYOR fixture must be publicly reachable at submit time.
  if (isRemoteFixture(sub.inputs.fixture)) {
    const fx = sub.inputs.fixture;
    if (!(await remoteFixtureReachable(fx.repo, fx.ref, fx.path))) {
      return NextResponse.json(
        {
          ok: false,
          error:
            "Your BYOR fixture is not publicly reachable at the pinned ref. Make the repo/file public and check the path.",
        },
        { status: 400 }
      );
    }
  }

  // 1c. Regions BED: required for coordinate-based tools, and it must fit the
  //     slice's supported-loci panel. The form checks this live, but that is UX,
  //     not enforcement — a direct POST must not get past it. Rejecting here also
  //     spares a CI run that the harness pre-flight would only abort anyway.
  const typeInfo = INPUT_TYPES.find((it) => it.slug === sub.inputs.type);
  if (typeInfo?.requiresRegions) {
    if (!sub.inputs.regions_bed) {
      return NextResponse.json(
        {
          ok: false,
          error:
            "This input type needs a regions BED: STRhub's reference BAM is a slice, so your tool must declare which supported loci to target.",
        },
        { status: 400 }
      );
    }
    const panel = sub.inputs.type ? await fetchPanel(sub.inputs.type) : null;
    // No panel for this type → we cannot prove the BED is out of scope, so we do
    // not reject. The harness pre-flight is the backstop.
    if (panel) {
      try {
        const result = validateRegions(
          parseBed3(sub.inputs.regions_bed),
          panel,
          typeInfo.minLoci ?? 5
        );
        if (!result.ok) {
          return NextResponse.json(
            {
              ok: false,
              error: `Your regions BED targets coordinates our reference slice does not cover, so your tool would find no reads there — this is not a failure of your tool. ${result.reasons.join("; ")}.`,
              regions: {
                outOfPanel: result.outOfPanel.map(
                  (r) => `${r.chrom}:${r.start}-${r.end} (line ${r.line})`
                ),
                coveredLoci: result.coveredLoci,
                panelSize: result.panelSize,
              },
            },
            { status: 400 }
          );
        }
      } catch (e) {
        return NextResponse.json(
          {
            ok: false,
            error: `Your regions BED is malformed: ${e instanceof Error ? e.message : "unparseable"}.`,
          },
          { status: 400 }
        );
      }
    }
  }

  // 2. Rate limit.
  const rate = await checkRateLimit(clientHash, sub.source.repo);
  if (!rate.ok) {
    return NextResponse.json({ ok: false, error: rate.reason }, { status: 429 });
  }

  try {
    // 3. Who owns this slug already, if anyone. Everything below turns on the
    //    difference between "the same author is back" and "someone else picked a
    //    name that collides", which the mere existence of the directory cannot
    //    tell apart.
    const owner = await manifestOwner(slug);
    const isOwnResubmission =
      owner !== null && normalizeRepo(owner) === normalizeRepo(sub.source.repo);

    // 3a. Slug taken by a different repository. Refuse rather than run: the
    //     manifest on disk belongs to someone else, so dispatching here would
    //     spend CI verifying THEIR tool while attributing the request to this
    //     submitter, and rewriting it would let anyone overwrite a stranger's
    //     verification contract by guessing a tool name and version.
    if (owner !== null && !isOwnResubmission) {
      return NextResponse.json(
        {
          ok: false,
          error:
            "That tool name and version are already registered to a different repository. Change the version (or the tool name) so your attestation gets its own permanent link.",
        },
        { status: 409 }
      );
    }

    // 3b. New-repo gate: hold for admin approval. Only the author's OWN
    //     re-submission skips it — an existing directory is not consent.
    if (!isOwnResubmission && !(await isRepoApproved(sub.source.repo))) {
      const pendingRecord = {
        slug,
        repo: sub.source.repo,
        ref: sub.source.ref,
        dispatchId: newDispatchId(),
        createdAt: new Date().toISOString(),
        clientHash,
        status: "approved-pending" as const,
        toolName: sub.tool.name,
        payload: JSON.stringify(parsed.data),
      };
      await recordSubmission(pendingRecord);
      notifyNewPendingSubmission({
        slug,
        toolName: sub.tool.name,
        toolVersion: sub.tool.version,
        repo: sub.source.repo,
        ip,
      }).catch((err) => console.error("verify/submit email error:", err));
      return NextResponse.json(
        {
          ok: true,
          status: "pending-approval",
          slug,
          message:
            "This repository is new to STRhub Verified and must be approved by an admin before its first run. You'll be able to resubmit once approved.",
        },
        { status: 202 }
      );
    }

    // 4. Commit metadata + dispatch.
    //    The manifest and Dockerfile are rebuilt from THIS submission every time,
    //    including re-submissions. They used to be written only when the directory
    //    was new, which silently discarded every edit: an author told by the
    //    diagnostics that a flag does not exist would fix the command, press
    //    "Edit & re-submit", and get the identical failure back with no
    //    indication why. That broke the promise the whole free tier rests on —
    //    that a correctable failure costs nothing to correct — so overwriting is
    //    the correct behaviour. It is safe only because 3a established that the
    //    slug belongs to this repository; a stranger never reaches this line.
    const dispatchId = newDispatchId();
    const alreadyExists = owner !== null;
    const msg = `verified: ${alreadyExists ? "update" : "add"} ${slug} (${sub.source.repo}@${sub.source.ref})`;
    await putFile(`tools/${slug}/manifest.yml`, buildManifestYaml(sub, slug), msg);
    await putFile(`tools/${slug}/Dockerfile`, generateDockerfile(sub), msg);
    if (sub.inputs.regions_bed) {
      await putFile(`tools/${slug}/${REGIONS_ASSET_PATH}`, sub.inputs.regions_bed, msg);
    }
    await dispatchWorkflow({ tool: slug, dispatch_id: dispatchId });

    await recordSubmission({
      slug,
      repo: sub.source.repo,
      ref: sub.source.ref,
      dispatchId,
      createdAt: new Date().toISOString(),
      clientHash,
      status: "dispatched",
    });

    return NextResponse.json(
      { ok: true, status: "dispatched", slug, dispatchId, engineRepo: ENGINE_REPO },
      { status: 201 }
    );
  } catch (e) {
    if (e instanceof GitHubConfigError) {
      console.error("verify/submit config error:", e.message);
      return NextResponse.json(
        { ok: false, error: "Server is not configured for submissions yet." },
        { status: 503 }
      );
    }
    if (e instanceof GitHubApiError) {
      console.error("verify/submit GitHub error:", e.message);
      return NextResponse.json(
        { ok: false, error: "GitHub API error while submitting.", status: e.status },
        { status: 502 }
      );
    }
    console.error("verify/submit error:", e);
    return NextResponse.json({ ok: false, error: "Internal error" }, { status: 500 });
  }
}
