/**
 * POST /api/verify/submit — self-service tool certification entry point.
 *
 * Flow (see plan §5, §10):
 *   1. Validate the submission against the manifest-mirroring zod schema.
 *   2. Rate-limit per client + per repo, BEFORE any outbound request.
 *   3. Check the inputs that would otherwise waste a CI run: the BYOR fixture is
 *      publicly reachable, and a regions BED fits the reference slice's panel.
 *   4. Resolve who owns the slug, from the committed manifest. A different repo
 *      is refused (409); only the same repo may overwrite and re-run.
 *   5. EVERY submission is held for admin approval → recorded as
 *      "approved-pending" and NOT dispatched until an admin approves it.
 *   6. (On approval, /api/verify/approve) Commit manifest.yml + Dockerfile to
 *      tools/<slug>/ and dispatch with a unique dispatch_id.
 *
 * STRhub never stores tool source code — only the verification metadata.
 */
import { type NextRequest, NextResponse } from "next/server";
import {
  submissionSchema,
  deriveSlug,
  newDispatchId,
  isRemoteFixture,
  INPUT_TYPES,
} from "@/lib/verified/submission";
import {
  parseBed3,
  validateRegions,
  fetchPanel,
} from "@/lib/verified/validate-regions";
import {
  GitHubConfigError,
  GitHubApiError,
  getFileContent,
} from "@/lib/verified/github";
import {
  checkRateLimit,
  hashClient,
  normalizeRepo,
  recordSubmission,
} from "@/lib/verified/store";
import { notifyNewPendingSubmission } from "@/lib/email";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

function clientIp(request: NextRequest): string {
  const fwd = request.headers.get("x-forwarded-for");
  if (fwd) return fwd.split(",")[0].trim();
  return request.headers.get("x-real-ip") || "unknown";
}

/**
 * Which repository a slug already belongs to, read from its committed manifest.
 *
 * A slug is derived from the tool name, version and input type, all of which the
 * submitter chooses, so two different repositories can land on the same one. That
 * makes "does tools/<slug>/manifest.yml exist?" the wrong question for both the
 * approval gate and the overwrite decision: it answers "is this slug taken", not
 * "is this the same author coming back". Returns null when there is no manifest.
 */
async function manifestOwner(slug: string): Promise<string | null> {
  const yml = await getFileContent(`tools/${slug}/manifest.yml`);
  if (!yml) return null;
  // The manifest is machine-generated by buildManifestYaml (or hand-written in the
  // same shape), so source.repo is a plain scalar on its own line.
  const m = yml.match(/^\s{2}repo:\s*["']?(\S+?)["']?\s*$/m);
  return m ? m[1] : null;
}

/**
 * The BYOR fixture must be PUBLIC at run time (§10). Verify the raw URL is
 * reachable before dispatching so the author gets a clear message instead of a
 * silently N/A "own" leg later.
 */
async function remoteFixtureReachable(
  repo: string,
  ref: string,
  path: string
): Promise<boolean> {
  const slug = repo.replace(/\.git$/, "").replace(/^https:\/\/github\.com\//, "");
  const url = `https://raw.githubusercontent.com/${slug}/${ref}/${path.replace(/^\//, "")}`;
  try {
    const res = await fetch(url, { method: "HEAD", cache: "no-store" });
    return res.ok;
  } catch {
    return false;
  }
}

export async function POST(request: NextRequest) {
  let body: unknown;
  try {
    body = await request.json();
  } catch {
    return NextResponse.json({ ok: false, error: "Invalid JSON body" }, { status: 400 });
  }

  const parsed = submissionSchema.safeParse(body);
  if (!parsed.success) {
    return NextResponse.json(
      { ok: false, error: "Validation failed", issues: parsed.error.flatten() },
      { status: 400 }
    );
  }
  const sub = parsed.data;
  const slug = deriveSlug(
    sub.tool.name,
    sub.tool.version,
    sub.inputs.type,
    sub.tool.variant,
  );
  // The raw address never leaves this request: records go to public repos, so
  // only the salted digest is stored. The address itself is used solely for the
  // admin notification email.
  const ip = clientIp(request);
  const clientHash = hashClient(ip);

  // 1b. Rate limit BEFORE anything that costs us work. The checks below each make
  //     an outbound request (a HEAD to raw.githubusercontent, a panel fetch), so
  //     running them first let an unthrottled caller drive our outbound traffic
  //     with requests that were going to be refused anyway.
  const rate = await checkRateLimit(clientHash, sub.source.repo);
  if (!rate.ok) {
    return NextResponse.json(
      { ok: false, error: rate.reason, retryAfterSeconds: rate.retryAfterSeconds },
      {
        status: 429,
        // The standard header for this, so a client that reads it does not have
        // to parse the sentence.
        headers: rate.retryAfterSeconds
          ? { "Retry-After": String(rate.retryAfterSeconds) }
          : undefined,
      }
    );
  }

  // 1c. BYOR fixture must be publicly reachable at submit time.
  if (isRemoteFixture(sub.inputs.fixture)) {
    const fx = sub.inputs.fixture;
    if (!(await remoteFixtureReachable(fx.repo, fx.ref, fx.path))) {
      return NextResponse.json(
        {
          ok: false,
          error:
            "Your BYOR fixture is not publicly reachable at the pinned ref. Make the repo/file public and check the path.",
        },
        { status: 400 }
      );
    }
  }

  // 1d. Regions BED: required for coordinate-based tools, and it must fit the
  //     slice's supported-loci panel. The form checks this live, but that is UX,
  //     not enforcement — a direct POST must not get past it. Rejecting here also
  //     spares a CI run that the harness pre-flight would only abort anyway.
  const typeInfo = INPUT_TYPES.find((it) => it.slug === sub.inputs.type);
  if (typeInfo?.requiresRegions) {
    if (!sub.inputs.regions_bed) {
      return NextResponse.json(
        {
          ok: false,
          error:
            "This input type needs a regions BED: STRhub's reference BAM is a slice, so your tool must declare which supported loci to target.",
        },
        { status: 400 }
      );
    }
    const panel = sub.inputs.type ? await fetchPanel(sub.inputs.type) : null;
    // No panel for this type → we cannot prove the BED is out of scope, so we do
    // not reject. The harness pre-flight is the backstop.
    if (panel) {
      try {
        const result = validateRegions(
          parseBed3(sub.inputs.regions_bed),
          panel,
          typeInfo.minLoci ?? 5
        );
        if (!result.ok) {
          return NextResponse.json(
            {
              ok: false,
              error: `Your regions BED targets coordinates our reference slice does not cover, so your tool would find no reads there — this is not a failure of your tool. ${result.reasons.join("; ")}.`,
              regions: {
                outOfPanel: result.outOfPanel.map(
                  (r) => `${r.chrom}:${r.start}-${r.end} (line ${r.line})`
                ),
                coveredLoci: result.coveredLoci,
                panelSize: result.panelSize,
              },
            },
            { status: 400 }
          );
        }
      } catch (e) {
        return NextResponse.json(
          {
            ok: false,
            error: `Your regions BED is malformed: ${e instanceof Error ? e.message : "unparseable"}.`,
          },
          { status: 400 }
        );
      }
    }
  }

  try {
    // 3. Who owns this slug already, if anyone. Everything below turns on the
    //    difference between "the same author is back" and "someone else picked a
    //    name that collides", which the mere existence of the directory cannot
    //    tell apart.
    const owner = await manifestOwner(slug);
    const isOwnResubmission =
      owner !== null && normalizeRepo(owner) === normalizeRepo(sub.source.repo);

    // 3a. Slug taken by a different repository. Refuse rather than run: the
    //     manifest on disk belongs to someone else, so dispatching here would
    //     spend CI verifying THEIR tool while attributing the request to this
    //     submitter, and rewriting it would let anyone overwrite a stranger's
    //     verification contract by guessing a tool name and version.
    if (owner !== null && !isOwnResubmission) {
      return NextResponse.json(
        {
          ok: false,
          error:
            "That tool name and version are already registered to a different repository. Change the version (or the tool name) so your attestation gets its own permanent link.",
        },
        { status: 409 }
      );
    }

    // 3b. Every submission is held for admin approval. This used to be skipped
    //     when the repository had been approved once before, or when the slug's
    //     manifest already named the same repository. Neither is evidence about
    //     the SUBMITTER: the repository URL is a field in an unauthenticated
    //     POST, so anyone could name an approved repository, attach an
    //     arbitrary Dockerfile (docker.mode "provided") and have it built and
    //     run in the engine's CI, then published as an attestation of that
    //     repository under its maintainer's name. Until a submission can prove
    //     control of the repository (a marker file at the pinned ref, planned),
    //     a human looks at every one. The commit + dispatch that used to follow
    //     here now lives only in /api/verify/approve, so the submitter does
    //     not need to come back.
    {
      const pendingRecord = {
        slug,
        repo: sub.source.repo,
        ref: sub.source.ref,
        dispatchId: newDispatchId(),
        createdAt: new Date().toISOString(),
        clientHash,
        status: "approved-pending" as const,
        toolName: sub.tool.name,
        payload: JSON.stringify(parsed.data),
      };
      await recordSubmission(pendingRecord);
      notifyNewPendingSubmission({
        slug,
        toolName: sub.tool.name,
        toolVersion: sub.tool.version,
        repo: sub.source.repo,
        ip,
      }).catch((err) => console.error("verify/submit email error:", err));
      return NextResponse.json(
        {
          ok: true,
          status: "pending-approval",
          slug,
          message:
            "Every submission is reviewed by a STRhub admin before it runs. Approval starts the run; you do not need to resubmit.",
        },
        { status: 202 }
      );
    }

  } catch (e) {
    if (e instanceof GitHubConfigError) {
      console.error("verify/submit config error:", e.message);
      return NextResponse.json(
        { ok: false, error: "Server is not configured for submissions yet." },
        { status: 503 }
      );
    }
    if (e instanceof GitHubApiError) {
      console.error("verify/submit GitHub error:", e.message);
      return NextResponse.json(
        { ok: false, error: "GitHub API error while submitting.", status: e.status },
        { status: 502 }
      );
    }
    console.error("verify/submit error:", e);
    return NextResponse.json({ ok: false, error: "Internal error" }, { status: 500 });
  }
}
