import type { Metadata } from "next";

export const SITE_URL = "https://strhub.app";
/** Default social card, generated by app/opengraph-image.tsx. */
export const OG_IMAGE = {
  url: "/opengraph-image",
  width: 1200,
  height: 630,
  alt: "STRhub, central hub for Short Tandem Repeats",
};
export const BASICS_LOCALES = ["en", "es", "pt"] as const;

/**
 * STRhub Verified is in a tester phase: reachable by direct link only.
 * Flip to true to add it to the header, footer and sitemap and let search
 * engines index it.
 */
export const VERIFIED_PUBLIC = false;
export type BasicsLocale = (typeof BASICS_LOCALES)[number];

export function isBasicsLocale(locale: string): locale is BasicsLocale {
  return BASICS_LOCALES.includes(locale as BasicsLocale);
}

export type PageMeta = {
  /** Page title without the site suffix; the root layout appends " | STRhub". */
  title: string | { absolute: string };
  description: string;
  /** Set to false for pages that must not be indexed (admin, search results). */
  index?: boolean;
} & Omit<Metadata, "title" | "description">;

/** Per-route metadata for server layouts: title, description, canonical and social cards. */
export function pageMetadata(path: string, meta: PageMeta): Metadata {
  const { title, description, index = true, openGraph, twitter, alternates, ...rest } =
    meta;
  const fullTitle =
    typeof title === "string" ? `${title} | STRhub` : title.absolute;
  return {
    // Set the final string explicitly: a nested layout that defines a plain
    // string title resets the root `title.template` for its children, so
    // relying on the template gives inconsistent suffixes.
    title: { absolute: fullTitle },
    description,
    alternates: {
      canonical: path,
      ...alternates,
    },
    openGraph: {
      title: fullTitle,
      description,
      url: path,
      siteName: "STRhub",
      type: "website",
      // A segment that defines `openGraph` replaces the root object entirely,
      // so the file-based /opengraph-image must be re-declared here.
      images: [OG_IMAGE],
      ...openGraph,
    },
    twitter: {
      card: "summary_large_image",
      title: fullTitle,
      description,
      images: [OG_IMAGE],
      ...twitter,
    },
    ...(index ? {} : { robots: { index: false, follow: true } }),
    ...rest,
  };
}

export function basicsArticlePath(locale: string, slug: string): string {
  return `/basics/${locale}/${slug}`;
}

export function basicsArticleAlternates(
  slug: string,
  locale: BasicsLocale,
  slugs?: Partial<Record<BasicsLocale, string>>
): NonNullable<Metadata["alternates"]> {
  const slugFor = (loc: BasicsLocale) => slugs?.[loc] || slugs?.en || slug;
  const languages: Record<string, string> = {
    "x-default": basicsArticlePath("en", slugFor("en")),
  };
  for (const loc of BASICS_LOCALES) {
    languages[loc] = basicsArticlePath(loc, slugFor(loc));
  }
  return {
    canonical: basicsArticlePath(locale, slugFor(locale)),
    languages,
  };
}

/**
 * Structured-data fields shared by every schema.org Dataset the site emits
 * (Search Console flags a Dataset without them).
 *
 * The licence is what STRhub grants on its own compilations (tables, charts,
 * downloads). The source data keep their own terms and are credited through
 * `isBasedOn` / `citation` on each Dataset. AGPL-3.0 is the licence of the
 * code, not of the data, so it is deliberately not used here.
 */
export const DATASET_LICENSE = "https://creativecommons.org/licenses/by/4.0/";

export const DATASET_CREATOR = {
  "@type": "Person",
  name: "Tamara Soledad Frontanilla Recalde",
  sameAs: [
    "https://orcid.org/0000-0002-6873-7813",
    "https://scholar.google.com/citations?user=wd4DwGIAAAAJ",
  ],
} as const;
