// Master catalog: single source of truth for tool existence and UI display.
// Used by /tools page and by marker Tools tab (filtered).

import type { ToolCard, UsageKey } from "./types";

// STRait Razor URLs (no longer read from marker toolsData)
const STRAITRAZOR_REPO = "https://github.com/Ahhgust/STRaitRazor";
const STRAITRAZOR_PAPER = "https://doi.org/10.1016/j.fsigen.2021.102463";
const STRAITRAZOR_ONLINE = "https://expectationsmanaged.shinyapps.io/STRaitRazoR/";

export function buildToolCards(t: (key: string) => string): ToolCard[] {
  const hasOnlineStraitRazor = true;

  return [
    {
      id: "strider",
      name: t("tools.strider.title"),
      summary: t("tools.strider.description"),
      technology: ["multi_platform"],
      read_type: ["any"],
      analysis: ["qc_database"],
      usage: ["online_tool"],
      features: [
        t("tools.strider.features.1"),
        t("tools.strider.features.2"),
        t("tools.strider.features.3"),
      ],
      input: "STR datasets",
      output: "QC reports / frequency data",
      website: "https://strider.online/",
      websiteLabel: t("tools.strider.buttons.website"),
    },
    {
      id: "strnaming",
      name: t("tools.strnaming.title"),
      summary: t("tools.strnaming.description"),
      technology: ["multi_platform"],
      read_type: ["any"],
      analysis: ["annotation"],
      usage: ["online_tool"],
      features: [
        t("tools.strnaming.features.1"),
        t("tools.strnaming.features.2"),
        t("tools.strnaming.features.3"),
      ],
      input: "STR sequence",
      output: "Allele nomenclature",
      website: "https://www.fdstools.nl/strnaming/index.html",
      websiteLabel: t("tools.strnaming.buttons.website"),
    },
    {
      id: "fdstools",
      name: t("tools.fdstools.title"),
      summary: t("tools.fdstools.description"),
      technology: ["illumina", "targeted"],
      read_type: ["short_read"],
      analysis: ["genotyping"],
      usage: ["runs_locally"],
      features: [
        t("tools.fdstools.features.1"),
        t("tools.fdstools.features.2"),
        t("tools.fdstools.features.3"),
      ],
      input: "NGS data (e.g. BAM, FASTQ from targeted MPS)",
      output: "Allele calls, stutter-filtered data, STRNaming nomenclature",
      website: "https://www.fdstools.nl/",
      websiteLabel: t("tools.fdstools.buttons.website"),
      github: "https://github.com/Jerrythafast/FDSTools",
      publication: "https://doi.org/10.1016/j.fsigen.2016.11.007",
    },
    {
      id: "hipstr",
      name: t("tools.hipstr.title"),
      summary: t("tools.hipstr.description"),
      technology: ["illumina"],
      read_type: ["short_read"],
      analysis: ["genotyping"],
      usage: ["runs_locally"],
      features: [
        t("tools.hipstr.features.1"),
        t("tools.hipstr.features.2"),
        t("tools.hipstr.features.3"),
      ],
      input: "BAM/CRAM (aligned short reads)",
      output: "VCF",
      github: "https://github.com/HipSTR-Tool/HipSTR",
      publication: "https://www.nature.com/articles/nmeth.4267",
      uiPublication:
        "https://www.fsigenetics.com/article/S1872-4973(26)00037-2/fulltext",
    },
    {
      id: "longtr",
      name: t("tools.longtr.title"),
      summary: t("tools.longtr.description"),
      technology: ["ont", "pacbio"],
      read_type: ["long_read"],
      analysis: ["genotyping"],
      usage: ["runs_locally"],
      features: [
        t("tools.longtr.features.1"),
        t("tools.longtr.features.2"),
        t("tools.longtr.features.3"),
        t("tools.longtr.features.4"),
      ],
      input: "BAM/CRAM (sorted & indexed), reference FASTA, TR regions BED",
      output: "bgzipped VCF",
      github: "https://github.com/gymrek-lab/LongTR",
      publication: "https://doi.org/10.1186/s13059-024-03319-2",
    },
    {
      id: "strspy",
      name: t("tools.strspy.title"),
      summary: t("tools.strspy.description"),
      technology: ["ont", "pacbio"],
      read_type: ["long_read"],
      analysis: ["genotyping"],
      usage: ["runs_locally"],
      features: [
        t("tools.strspy.features.1"),
        t("tools.strspy.features.2"),
        t("tools.strspy.features.3"),
      ],
      input: "FASTQ, BAM (ONT)",
      output: "TXT/TSV tables",
      github: "https://github.com/unique379r/strspy/tree/main",
      publication: "https://pubmed.ncbi.nlm.nih.gov/34837788/",
    },
    {
      id: "gangstr",
      name: t("tools.gangstr.title"),
      summary: t("tools.gangstr.description"),
      technology: ["illumina"],
      read_type: ["short_read"],
      analysis: ["genotyping"],
      usage: ["runs_locally"],
      features: [
        t("tools.gangstr.features.1"),
        t("tools.gangstr.features.2"),
        t("tools.gangstr.features.3"),
      ],
      input: "BAM (short-read aligned)",
      output: "VCF",
      github: "https://github.com/gymreklab/GangSTR",
      publication: "https://pubmed.ncbi.nlm.nih.gov/31194863/",
    },
    {
      id: "straitrazor",
      name: t("tools.straitrazor.title"),
      summary: t("tools.straitrazor.description"),
      technology: ["illumina", "targeted"],
      read_type: ["short_read"],
      analysis: ["genotyping"],
      usage: hasOnlineStraitRazor
        ? (["runs_locally", "online_tool", "graphical_interface"] as UsageKey[])
        : ["runs_locally"],
      features: [
        t("tools.straitrazor.features.1"),
        t("tools.straitrazor.features.2"),
        t("tools.straitrazor.features.3"),
      ],
      input: "FASTQ (Illumina)",
      output: "Tabular (TSV/CSV/TXT)",
      github: STRAITRAZOR_REPO,
      publication: STRAITRAZOR_PAPER,
      website: STRAITRAZOR_ONLINE,
      websiteLabel: hasOnlineStraitRazor
        ? t("tools.straitrazor.buttons.online")
        : undefined,
    },
    {
      id: "toastr",
      name: t("tools.toastr.title"),
      summary: t("tools.toastr.description"),
      technology: ["illumina"],
      read_type: ["short_read"],
      analysis: ["genotyping"],
      usage: ["runs_locally"],
      features: [
        t("tools.toastr.features.1"),
        t("tools.toastr.features.2"),
        t("tools.toastr.features.3"),
      ],
      input: "FASTA (repeat definitions), FASTQ (reads)",
      output: "Tabular allele calls and STR structural summary",
      github: "https://github.com/labconowl/toastr",
      publication: "https://www.fsigenetics.com/article/S1872-4973(18)30063-2/fulltext",
    },
    {
      id: "nanomnt",
      name: t("tools.nanomnt.title"),
      summary: t("tools.nanomnt.summary"),
      technology: ["ont"],
      read_type: ["long_read"],
      analysis: ["genotyping"],
      usage: ["runs_locally"],
      features: [
        t("tools.nanomnt.features.1"),
        t("tools.nanomnt.features.2"),
        t("tools.nanomnt.features.3"),
      ],
      input: "BAM (aligned long reads)",
      output: "Tabular (TSV/CSV/TXT)",
      github: "https://github.com/18parkky/NanoMnT",
      publication: "https://doi.org/10.1093/gigascience/giaf013",
    },
    {
      id: "strkit",
      name: t("tools.strkit.title"),
      summary: t("tools.strkit.summary"),
      technology: ["ont", "pacbio"],
      read_type: ["long_read"],
      analysis: ["genotyping"],
      usage: ["runs_locally"],
      features: [
        t("tools.strkit.features.1"),
        t("tools.strkit.features.2"),
        t("tools.strkit.features.3"),
      ],
      input: "FASTQ, BAM (long-read)",
      output: "Tabular (TSV/CSV/TXT)",
      github: "https://github.com/davidlougheed/strkit",
      publication: "https://doi.org/10.1101/2025.03.25.645269",
    },
    {
      id: "nastra",
      name: t("tools.nastra.title"),
      summary: t("tools.nastra.summary"),
      technology: ["ont"],
      read_type: ["long_read"],
      analysis: ["genotyping"],
      usage: ["runs_locally"],
      features: [
        t("tools.nastra.features.1"),
        t("tools.nastra.features.2"),
        t("tools.nastra.features.3"),
      ],
      input: "FASTQ, BAM (long-read)",
      output: "Tabular (TSV/CSV/TXT)",
      github: "https://github.com/renzilin/NASTRA",
      publication: "https://doi.org/10.1093/bib/bbae472",
    },
    {
      id: "nanostr",
      name: t("tools.nanostr.title"),
      summary: t("tools.nanostr.summary"),
      technology: ["ont"],
      read_type: ["long_read"],
      analysis: ["genotyping"],
      usage: ["runs_locally"],
      features: [
        t("tools.nanostr.features.1"),
        t("tools.nanostr.features.2"),
        t("tools.nanostr.features.3"),
      ],
      input: "FASTQ (long-read)",
      output: "Tabular (TSV/CSV/TXT)",
      github: "https://github.com/langjidong/NanoSTR",
      publication:
        "https://www.frontiersin.org/articles/10.3389/fmolb.2023.1093519/full",
    },
  ];
}
